{
    'name': 'Barca Mantenimiento',
    'version': '1.1',
    'summary': 'Módulo de mantención de flota Barca SpA',
    'category': 'Operations',
    'depends': [
        'fleet',
        'hr_fleet',
        'zhr_ajustes',
        'maintenance',
        'stock',
        'mail',
        'web',
        'website',
        'zweb_offline_forms',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/fleet_alert_rule_data.xml',
        'data/cron_fleet_expiration_alerts.xml',
        'data/maintenance_alert_sequence.xml',
        'data/maintenance_request_simple_sequence.xml',
        'data/maintenance_checklist_sequence.xml',
        'data/maintenance_checklist_items.xml',
        'data/maintenance_stage_data.xml',
        'data/checklist_offline_form.xml',
        'views/technical_location_views.xml',
        'views/intervention_type_views.xml',
        'views/maintenance_activity_views.xml',
        'views/maintenance_plan_views.xml',
        'views/maintenance_kit_views.xml',
        'views/maintenance_request_views.xml',
        'views/base_views.xml',
        'views/fleet_alert_rule_views.xml',
        'views/maintenance_request_simple_views.xml',
        'views/maintenance_checklist_views.xml',
        'views/maintenance_alert_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/fleet_vehicle_log_contract_views.xml',
        'data/cron.xml',
        'data/cron_pm_alerts.xml',
        'templates/checklist_website.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'zmm_ajustes/static/src/js/workorder_activity_start_button.js',
        ],
    },
    'installable': True,
    'application': True,
    'post_init_hook': 'sync_existing_vehicle_equipment',
}
