{
    'name': 'Barca Mantenimiento',
    'version': '1.0',
    'summary': 'Módulo de mantención de flota Barca SpA',
    'category': 'Operations',
    'depends': ['fleet', 'maintenance', 'stock', 'purchase', 'mail'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/maintenance_alert_sequence.xml',
        'views/technical_location_views.xml',
        'views/intervention_type_views.xml',
        'views/maintenance_plan_views.xml',
        'views/maintenance_kit_views.xml',
        'views/base_views.xml',
        'views/maintenance_alert_views.xml',
        'views/fleet_vehicle_views.xml',
        'data/cron.xml',
    ],
    'installable': True,
    'application': True,
    'post_init_hook': 'load_technical_locations',
}
