from . import fleet_vehicle
from . import fleet_vehicle_log_services
from . import intervention_type
from . import technical_location
from . import maintenance_activity
from . import maintenance_plan_line
from . import maintenance_plan
from . import maintenance_equipment
from . import maintenance_kit
from . import maintenance_alert
from . import maintenance_request
